### ISSUE TITLE
Wrong label for size in Bytes

### ISSUE THREAD

**Issue by andrea-manzi** [calvellido/DPMbox#15]
Hi Juan,
i think the label for the size in bytes is Wrong. I never saw representing Bytes as "Bt", so i believe you should remove it, for instance instead of 491 Bt, you should display only 491 ( this is how the previous gui is doing and also the linux files sizes are shown via shell), 
thanks
cheers
Andrea

**Comment by calvellido** [comment]
Yes, I see what you mean. This is now corrected and the sizes will be shown like this from now on:

![screenshot1](https://cloud.githubusercontent.com/assets/7753447/7316374/c04d407e-ea76-11e4-9335-49c5ea70811c.png)

Thanks for the feedback Andrea!
